<?php

/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */

/*
 * Dati:
nome
gusto
linea(strong o light) --> radio
gassata(si o no)
preferita della classe: 5ci, 4ci ecc. (menu a tendina)
calorie (checkbox)
sede di produzione(in caso lo facciamo è da cambiare l’organigramma)
 * 
Linea Light:
EnerLITE Fusion (Gusto: Frutta Tropicale)
ZeroCharge Zest (Gusto: Limone e Menta)
PureVibe Spark (Gusto: Ciliegia Esplosiva)
CalorieCrush Essence (Gusto: Arancia Rivitalizzante)
RefreshZero Burst (Gusto: Melograno Rinfrescante)
ZenBoost Elixir (Gusto: Pesca Serena)
VitalWave Harmony (Gusto: Limetta Fresca)
CrystalCharge Wave (Gusto: Acai Crystal)
RadiantFuel Essence (Gusto: Zenzero Radiante)
PureBurst Revive (Gusto: Bacche Selvatiche)


Linea Strong:
PowerPunch Intensity (Gusto: Mirtillo Elettrico)
MegaFuel Surge (Gusto: Lampone Potente)
XtremeVital Blitz (Gusto: Agrumi Estremi)
TurboThirst Revolt (Gusto: Cola Shock)
HyperDrive Ignition (Gusto: Mela Cannella Ardente)
ThunderFuel Storm (Gusto: Ananas Tempesta)
UltraIgnite Blaze (Gusto: Frutto della Passione Ardente)
MegaVortex Fury (Gusto: Kiwi Vorticoso)
InfernoPower Surge (Gusto: Caffè Espresso)
TurboFusion Burst (Gusto: Limone Piccante)

 */

$prodotti = array(
    array('nome' => '', 'linea' => '', 'gassata' => '', 'preferita' => '', 'calorie' => 0, 'collab' => '' , 'img-prodotto' => ''),
    array('nome' => '', 'linea' => '', 'gassata' => '', 'preferita' => '', 'calorie' => 0, 'collab' => '' , 'img-prodotto' => ''),
    array('nome' => '', 'linea' => '', 'gassata' => '', 'preferita' => '', 'calorie' => 0, 'collab' => '' , 'img-prodotto' => ''),
    array('nome' => '', 'linea' => '', 'gassata' => '', 'preferita' => '', 'calorie' => 0, 'collab' => '' , 'img-prodotto' => ''),
    array('nome' => '', 'linea' => '', 'gassata' => '', 'preferita' => '', 'calorie' => 0, 'collab' => '' , 'img-prodotto' => ''),
    array('nome' => '', 'linea' => '', 'gassata' => '', 'preferita' => '', 'calorie' => 0, 'collab' => '' , 'img-prodotto' => ''),
    array('nome' => '', 'linea' => '', 'gassata' => '', 'preferita' => '', 'calorie' => 0, 'collab' => '' , 'img-prodotto' => ''),
    array('nome' => '', 'linea' => '', 'gassata' => '', 'preferita' => '', 'calorie' => 0, 'collab' => '' , 'img-prodotto' => ''),
    array('nome' => '', 'linea' => '', 'gassata' => '', 'preferita' => '', 'calorie' => 0, 'collab' => '' , 'img-prodotto' => ''),
    
);