<?php

$utenti = array(
    'superuser' => array ('password' => 'pwd1', 'ruolo' => 'admin', 'nome' => 'amministratore', 'cognome' => 'admin'),
    'utente1' => array('password' => 'surry', 'ruolo' => 'visitatore', 'nome' => 'Salvatore', 'cognome' => 'Cinquegrana'),
    'utente2' => array('password' => 'mhahah', 'ruolo' => 'visitatore', 'nome' => 'Gabriele Diss Gacha', 'cognome' => 'Pastero Dai Spingi aka Offeset'),
    'utente3' => array('password' => 'no', 'ruolo' => 'visitatore', 'nome' => 'Peixe', 'cognome' => 'Musolini'),
    'grandeGhapow' => array('password' => 'admin', 'ruolo' => 'admin', 'nome' => 'Davide', 'cognome' => 'Gamberini')
);